import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Oasis",
  description: "Generated by create next app",
  icons:{
    icon:['/public/favicon.ico?v=4'],
    apple:['/public/apple-touch-icon.png?v=4']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
